import './_group.css';
import type React from 'react';
import { ArrowRight, ArrowUpRight, Briefcase, CalendarCheck, ChevronRight, ClipboardList, Clock, MapPin, Search, Send, ShieldCheck, UserCheck, Users } from 'lucide-react';

const jobs = [
  { company:'Waldorf Astoria Maldives Ithaafushi', title:'Chef de Partie - Pastry', location:'South Malé Atoll', description:'Join a world-class culinary team delivering exceptional dining experiences in an iconic island setting.', deadline:'18 Jun 2025', tags:['Accommodation provided','Service charge'] },
  { company:'Patina Maldives, Fari Islands', title:'Guest Relations Officer', location:'North Malé Atoll', description:'Create thoughtful, personal moments for guests at one of the Maldives’ most distinctive island resorts.', deadline:'24 Jun 2025', tags:['Full-time','Resort experience'] },
  { company:'Sun Siyam Olhuveli', title:'Recreation Supervisor', location:'South Malé Atoll', description:'Lead memorable experiences and a confident recreation team across our lagoon and island facilities.', deadline:'Ongoing', tags:['Maldives experience'] },
  { company:'Kuredu Island Resort & Spa', title:'Front Office Agent', location:'Lhaviyani Atoll', description:'Be the welcoming face of a beloved island resort, from arrival through every guest interaction.', deadline:'30 Jun 2025', tags:['Languages','Guest service'] },
];
const steps = [[Briefcase,'Vacancy Posted'],[Send,'Applications'],[Search,'Expert Screening'],[UserCheck,'Manual Review'],[ClipboardList,'Shortlist Built'],[Users,'Employer Interview']] as const;

const Button = ({children, dark=false}:{children:React.ReactNode;dark?:boolean}) => <a href="#jobs" className={`inline-flex items-center justify-center gap-2 px-7 h-14 font-semibold text-sm rounded-sm transition-transform hover:-translate-y-1 ${dark?'bg-white text-[#101d3b]':'bg-[#e5b33c] text-[#101d3b]'}`}>{children}</a>;
export function Current() {
 return <main className="jobs-visual bg-[#f8fafc]">
  <header className="h-20 bg-white border-b border-[#e2e7ee] flex items-center justify-between px-5 md:px-10 sticky top-0 z-20">
   <a href="#" className="flex items-center gap-2"><img src="/__mockup/images/logo_final.png" className="w-11 h-11 rounded-full" alt="The Jobs MV"/><b className="font-display text-xl text-[#101d3b]">The Jobs MV</b></a>
   <nav className="hidden md:flex gap-8 text-sm font-medium text-[#40506a]"><a href="#jobs">Find Jobs</a><a href="#passport">Hospitality Passport</a><a href="#employers">Companies</a></nav>
   <div className="hidden md:flex gap-3 items-center"><a href="#employers" className="text-sm font-semibold">Employer Workspace</a><a href="#jobs" className="rounded-full bg-[#101d3b] text-white px-5 py-3 text-sm font-semibold">Find Jobs</a></div>
   <a href="#jobs" className="md:hidden text-[#101d3b] text-sm font-bold">Menu</a>
  </header>
  <section className="relative min-h-[680px] h-[calc(100svh-80px)] max-h-[900px] overflow-hidden bg-[#101d3b] flex items-end">
   <img src="/__mockup/images/maldives_hero.jpg" alt="Maldives resort over turquoise water" className="absolute inset-0 w-full h-full object-cover object-center jobs-pan"/>
   <div className="absolute inset-0 bg-gradient-to-t from-[#101d3b] via-[#101d3b]/65 to-[#101d3b]/10"/>
   <div className="relative z-10 max-w-7xl w-full mx-auto px-5 md:px-10 pb-20 md:pb-28 jobs-rise">
    <div className="inline-flex items-center gap-3 border border-white/20 bg-white/10 px-3 py-2 text-[11px] tracking-[.2em] uppercase text-white mb-8"><i className="w-2 h-2 rounded-full bg-[#e5b33c]"/>The Premium Network</div>
    <h1 className="text-5xl md:text-7xl lg:text-[5.5rem] leading-[1.02] font-semibold text-white max-w-4xl">Elevating Maldives<br/><em className="text-[#e5b33c] font-normal">hospitality</em> careers.</h1>
    <p className="mt-7 text-lg md:text-2xl font-light leading-relaxed text-white/80 max-w-2xl">We bridge the gap between world-class resorts and the professionals who bring them to life. Right Talent. Right Opportunity. Right Time.</p>
    <div className="flex flex-col sm:flex-row gap-4 mt-9"><Button>Explore Opportunities <ArrowRight size={18}/></Button><Button dark>Hire with Confidence</Button></div>
   </div>
  </section>
  <section id="jobs" className="py-24 md:py-32 px-5 md:px-10 max-w-7xl mx-auto">
   <div className="flex justify-between items-end mb-14"><div><p className="uppercase tracking-[.18em] text-[#1688a3] font-bold text-xs flex items-center gap-2"><Clock size={15}/> Active Vacancies</p><h2 className="text-4xl md:text-6xl font-semibold mt-4">Current Opportunities</h2></div><a href="#" className="hidden sm:flex items-center gap-2 text-[#1688a3] font-semibold">View all positions <ArrowRight size={18}/></a></div>
   <div className="border-y border-[#dce2ea]">{jobs.map((job,i)=><a href="#" key={job.title} className="group grid md:grid-cols-12 gap-6 py-9 md:py-11 border-b last:border-0 border-[#dce2ea] hover:bg-white transition-colors px-2">
    <div className="md:col-span-3"><b className="text-lg">{job.company}</b><div className="text-sm text-[#66738a] mt-3 flex items-center gap-1"><MapPin size={14}/>{job.location}</div><span className="inline-flex items-center gap-1 mt-3 text-[11px] font-bold text-[#101d3b] bg-[#e9f2f5] px-2 py-1"><ShieldCheck size={13}/> Verified Employer</span></div>
    <div className="md:col-span-6"><h3 className="text-2xl md:text-3xl font-semibold group-hover:text-[#1688a3] transition-colors">{job.title}</h3><p className="text-[#66738a] mt-3 leading-relaxed">{job.description}</p><div className="flex flex-wrap gap-2 mt-4">{job.tags.map(x=><span key={`${job.title}-${x}`} className="text-xs border border-[#dce2ea] px-3 py-1">{x}</span>)}</div></div>
    <div className="md:col-span-3 flex md:flex-col justify-between items-start md:items-end gap-4 border-t md:border-0 pt-4 md:pt-0"><span className={`text-xs font-semibold px-2.5 py-1 ${job.deadline==='Ongoing'?'bg-[#edf0f3] text-[#66738a]':'bg-[#fff5e7] text-[#a65f15]'}`}>{job.deadline==='Ongoing'?'Ongoing':<><CalendarCheck size={13} className="inline mr-1"/>Closes {job.deadline}</>}</span><span className="w-11 h-11 rounded-full border border-[#dce2ea] flex items-center justify-center group-hover:bg-[#1688a3] group-hover:text-white transition-colors"><ArrowUpRight size={19}/></span></div>
   </a>)}</div>
  </section>
  <section id="passport" className="bg-[#101d3b] text-white py-24 md:py-32 px-5 md:px-10 relative overflow-hidden"><div className="absolute -right-40 -top-40 w-[600px] h-[600px] border border-white/10 rounded-full"/><div className="max-w-7xl mx-auto grid lg:grid-cols-12 gap-14 items-center relative"><div className="lg:col-span-5"><p className="text-[#e5b33c] uppercase tracking-[.2em] text-xs font-bold">Hospitality Passport</p><h2 className="text-4xl md:text-6xl font-semibold leading-[1.05] mt-5">One Profile.<br/><em className="text-white/55 font-normal">Every Opportunity.</em></h2><p className="text-white/70 text-lg leading-relaxed mt-7">Build a single, comprehensive professional identity. Highlight your experience, skills, and availability once. Apply instantly and help employers understand your true value beyond a traditional CV.</p><Button dark>Create Passport <ChevronRight size={18}/></Button></div><div className="lg:col-span-6 lg:col-start-7 grid sm:grid-cols-2 gap-3">{['Experience','Maldives Experience','Resort Experience','Skills','Certifications','Languages','Availability','Notice Period'].map(x=><div key={x} className="border border-white/10 bg-white/5 p-5 flex justify-between text-sm"><span>{x}</span><i className="w-1.5 h-1.5 rounded-full bg-[#e5b33c]"/></div>)}</div></div></section>
  <section className="py-24 md:py-32 px-5 md:px-10 bg-[#f1f4f7]"><div className="max-w-3xl mx-auto text-center"><p className="text-[#1688a3] uppercase tracking-[.18em] text-xs font-bold">The Jobs MV Reviewed</p><h2 className="text-4xl md:text-5xl font-semibold mt-4">Expert screening.<br/>Human review.</h2><p className="text-[#66738a] text-lg leading-relaxed mt-6">Our experts help identify strong matches. We manually review shortlisted candidates before presenting them to employers, ensuring credibility on both sides.</p></div><div className="max-w-5xl mx-auto mt-16 grid grid-cols-2 md:grid-cols-6 gap-8 relative">{steps.map(([Icon,label],i)=><div key={label} className="text-center group"><div className="mx-auto w-16 h-16 rounded-full bg-white border border-[#dce2ea] flex items-center justify-center group-hover:border-[#1688a3] transition-colors"><Icon size={23}/></div><small className="block text-[#8792a4] font-mono mt-4">0{i+1}</small><b className="text-sm leading-tight block mt-1">{label}</b></div>)}</div></section>
  <section id="employers" className="py-24 md:py-32 px-5 md:px-10"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"><div><p className="text-[#1688a3] uppercase tracking-[.18em] text-xs font-bold">Employer Services</p><h2 className="text-4xl md:text-6xl font-semibold leading-[1.05] mt-5">Don't lose great talent because hiring takes too long.</h2><p className="text-[#66738a] text-lg leading-relaxed mt-7">Tell us who you need. We help screen applications, identify strong candidates and build an interview-ready shortlist, so you can focus on running your business.</p><div className="border-l-2 border-[#e5b33c] bg-[#f7f9fa] px-5 py-4 mt-7 font-semibold">Recruitment support for resorts, hotels, guesthouses and hospitality businesses.</div><div className="flex flex-wrap gap-4 mt-8"><Button>Request Candidates <ArrowRight size={18}/></Button><a href="#" className="h-14 border border-[#dce2ea] px-7 inline-flex items-center font-semibold">Post a Vacancy</a></div></div><div className="relative aspect-square overflow-hidden"><img src="/__mockup/images/hero_banner.png" alt="Hospitality professionals" className="w-full h-full object-cover"/><div className="absolute inset-4 border border-white/40"/><div className="absolute bottom-7 left-7 right-7 bg-white/95 p-6"><h3 className="text-lg font-semibold">Expert Screening</h3><p className="text-sm text-[#66738a] mt-1">We help employers manage applications and build focused shortlists.</p></div></div></div></section>
  <section className="bg-[#101d3b] text-white text-center py-24 md:py-32 px-5"><p className="text-[#e5b33c] uppercase tracking-[.2em] text-xs font-bold">Why We Exist</p><h2 className="text-4xl md:text-7xl font-semibold max-w-5xl mx-auto mt-7">Great talent should never be lost to a slow hiring process.</h2><p className="text-white/70 max-w-3xl mx-auto text-xl leading-relaxed mt-8">We make hospitality recruitment faster and simpler, helping employers find the right people and job seekers reach the right opportunities when they matter most.</p><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-px bg-white/10 mt-16 text-left"><div className="bg-[#101d3b] p-10"><h3 className="text-2xl font-semibold">People First</h3><p className="text-white/65 text-lg mt-4 leading-relaxed">Behind every CV is a person looking for an opportunity. Behind every vacancy is a team looking for the right person.</p></div><div className="bg-[#101d3b] p-10"><h3 className="text-2xl font-semibold">Time Matters</h3><p className="text-white/65 text-lg mt-4 leading-relaxed">Great talent doesn't wait forever. We help employers and job seekers connect before opportunities are lost.</p></div></div><p className="text-[#e5b33c] text-2xl md:text-4xl italic font-semibold mt-20">Right Talent. Right Opportunity. Right Time.</p></section>
 </main>;
}