import './_group.css';
import './_refined.css';
import type React from 'react';
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Compass, Menu, Search, ShieldCheck } from 'lucide-react';

const opportunities = [
 { no:'01', role:'Chef de Partie — Pastry', property:'Waldorf Astoria Maldives Ithaafushi', place:'South Malé Atoll', close:'18 Jun 2025', note:'Accommodation provided · Service charge' },
 { no:'02', role:'Guest Relations Officer', property:'Patina Maldives, Fari Islands', place:'North Malé Atoll', close:'24 Jun 2025', note:'Full-time · Resort experience' },
 { no:'03', role:'Recreation Supervisor', property:'Sun Siyam Olhuveli', place:'South Malé Atoll', close:'Ongoing', note:'Maldives experience' },
 { no:'04', role:'Front Office Agent', property:'Kuredu Island Resort & Spa', place:'Lhaviyani Atoll', close:'30 Jun 2025', note:'Languages · Guest service' },
];
const LinkButton = ({children, pale=false}:{children:React.ReactNode;pale?:boolean}) => <a href="#opportunities" className={`inline-flex items-center gap-3 px-6 py-4 text-xs font-bold uppercase tracking-[.12em] transition-all hover:gap-5 ${pale?'bg-[#f5efe2] text-[#12243f]':'bg-[#dba933] text-[#12243f]'}`}>{children}</a>;

export function RefinedEditorial() {
 return <main className="jobs-visual refined-editorial bg-[#f5f2ec] text-[#12243f] overflow-hidden">
  <nav className="absolute z-30 top-0 left-0 right-0 max-w-[1440px] mx-auto px-6 md:px-12 h-24 flex items-center justify-between text-white"><a href="#" className="flex items-center gap-3"><img src="/__mockup/images/logo_final.png" className="w-12 h-12 rounded-full" alt="The Jobs MV"/><span className="font-display text-xl font-semibold tracking-tight">The Jobs MV</span></a><div className="hidden md:flex items-center gap-10 text-[11px] uppercase tracking-[.16em] font-bold"><a href="#opportunities" className="text-[#e8c56a]">Find roles</a><a href="#passport">Passport</a><a href="#employers">For employers</a></div><a href="#opportunities" className="hidden md:flex items-center gap-2 text-[11px] uppercase tracking-[.16em] font-bold border border-white/35 px-5 py-3">Browse jobs <ArrowUpRight size={15}/></a><Menu className="md:hidden"/></nav>
  <section className="min-h-[760px] md:h-[800px] relative bg-[#12243f] text-white flex items-end">
   <img src="/__mockup/images/maldives_hero.jpg" alt="Aerial view of a Maldives resort" className="absolute inset-0 h-full w-full object-cover object-center jobs-pan opacity-85"/>
   <div className="absolute inset-0 bg-[linear-gradient(110deg,#12243f_0%,rgba(18,36,63,.72)_38%,rgba(18,36,63,.08)_100%)]"/><div className="absolute inset-0 bg-gradient-to-t from-[#12243f] via-transparent to-transparent"/>
   <div className="relative z-10 max-w-[1440px] w-full mx-auto px-6 md:px-12 pb-20 md:pb-24 grid lg:grid-cols-12 gap-8 items-end">
    <div className="lg:col-span-8 jobs-rise"><p className="text-[#e8c56a] text-[11px] uppercase tracking-[.3em] font-bold mb-8">A career, somewhere extraordinary</p><h1 className="font-display text-6xl sm:text-7xl md:text-[8rem] leading-[.88] font-medium tracking-[-.05em]">Find your<br/><i className="font-normal text-[#e8c56a]">island.</i></h1><p className="max-w-lg text-white/75 text-base md:text-lg leading-relaxed mt-9">Current opportunities across the Maldives, for the people who make every stay unforgettable.</p><div className="flex flex-wrap gap-3 mt-8"><LinkButton>Explore current roles <ArrowRight size={17}/></LinkButton><LinkButton pale>Build your Passport <ChevronRight size={17}/></LinkButton></div></div>
    <div className="hidden lg:block lg:col-span-4 border-l border-white/25 pl-8 pb-2"><p className="text-[10px] uppercase tracking-[.24em] text-white/55">The Jobs MV / 01</p><p className="font-display text-3xl mt-4 leading-tight">Right talent.<br/><span className="text-[#e8c56a]">Right time.</span></p><a href="#story" className="inline-flex items-center gap-2 mt-12 text-xs uppercase tracking-[.14em] font-bold">Our point of view <ArrowDownRight size={16}/></a></div>
   </div>
  </section>
  <section id="opportunities" className="max-w-[1440px] mx-auto px-6 md:px-12 py-24 md:py-32"><div className="flex flex-col md:flex-row md:justify-between md:items-end gap-8"><div><p className="text-[#b37a19] text-[11px] uppercase tracking-[.25em] font-bold">The noticeboard / live</p><h2 className="font-display text-5xl md:text-7xl font-medium tracking-[-.04em] mt-4">Open water,<br/><i className="font-normal text-[#b37a19]">open roles.</i></h2></div><div className="max-w-xs text-sm text-[#637187] leading-relaxed md:text-right">A considered shortlist of current hospitality roles. Read the detail, then make your move.</div></div>
   <div className="mt-20 border-t-2 border-[#12243f]">{opportunities.map((job)=><a key={job.no} href="#" className="grid md:grid-cols-12 gap-5 py-8 border-b border-[#cfd0cc] group hover:bg-[#eee9df] -mx-3 px-3 transition-colors"><span className="md:col-span-1 text-[#b37a19] font-mono text-xs pt-1">{job.no}</span><div className="md:col-span-5"><h3 className="font-display text-2xl md:text-3xl font-medium group-hover:italic transition-all">{job.role}</h3><p className="mt-2 text-sm text-[#637187]">{job.property}</p></div><div className="md:col-span-3 text-sm text-[#637187] flex items-start gap-2"><Compass size={15} className="mt-0.5 shrink-0"/>{job.place}</div><div className="md:col-span-2 text-xs uppercase tracking-[.08em] font-bold md:text-right">{job.close==='Ongoing'?job.close:<><CalendarDays size={14} className="inline mr-2 text-[#b37a19]"/>Closes {job.close}</>}</div><div className="md:col-span-1 flex justify-end"><span className="w-10 h-10 rounded-full border border-[#bfc3c0] flex items-center justify-center group-hover:bg-[#12243f] group-hover:text-white transition-colors"><ArrowUpRight size={17}/></span></div><p className="md:col-start-2 md:col-span-6 text-xs text-[#637187]">{job.note}</p></a>)}</div>
   <a href="#" className="inline-flex items-center gap-2 mt-10 text-xs uppercase tracking-[.16em] font-bold border-b border-[#12243f] pb-2">See every opportunity <ArrowRight size={16}/></a>
  </section>
  <section id="passport" className="bg-[#12243f] text-white relative"><div className="max-w-[1440px] mx-auto grid lg:grid-cols-2 min-h-[680px]"><div className="p-8 md:p-16 lg:p-24 flex flex-col justify-center"><p className="text-[#e8c56a] text-[11px] uppercase tracking-[.25em] font-bold">Hospitality Passport / your profile</p><h2 className="font-display text-5xl md:text-7xl font-medium leading-[.95] tracking-[-.04em] mt-6">More than<br/><i className="text-[#e8c56a] font-normal">a CV.</i></h2><p className="text-white/65 max-w-md leading-relaxed mt-8">One thoughtful profile for every opportunity. Show employers the experience, skills and availability that make you, you.</p><a href="#" className="mt-9 inline-flex items-center gap-3 text-[#e8c56a] uppercase tracking-[.14em] text-xs font-bold">Create your Passport <ArrowRight size={17}/></a></div><div className="relative min-h-[420px]"><img src="/__mockup/images/hero_banner.png" alt="Hospitality professionals" className="absolute inset-0 w-full h-full object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-r from-[#12243f] via-transparent to-transparent"/><div className="absolute bottom-10 left-8 right-8 md:left-16 md:right-16 border-t border-white/35 pt-5 grid grid-cols-2 gap-y-4 text-sm">{['Experience','Maldives Experience','Skills','Certifications','Languages','Availability'].map(x=><span key={x} className="flex items-center gap-2 text-white/80"><Check size={14} className="text-[#e8c56a]"/>{x}</span>)}</div></div></div></section>
  <section id="story" className="max-w-[1440px] mx-auto px-6 md:px-12 py-24 md:py-32"><div className="grid lg:grid-cols-12 gap-12"><div className="lg:col-span-4"><p className="text-[#b37a19] text-[11px] uppercase tracking-[.25em] font-bold">The network / reviewed</p><h2 className="font-display text-5xl md:text-6xl mt-5 leading-[.95]">A human<br/><i>signal</i> in<br/>the noise.</h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="text-xl md:text-2xl leading-relaxed max-w-2xl">We manually review shortlisted candidates before presenting them to employers. It is a simple promise: make the introduction credible on both sides.</p><div className="grid sm:grid-cols-3 gap-8 mt-16 border-t border-[#cfd0cc] pt-8">{[['01','Applications'],['02','Expert screening'],['03','Employer interview']].map(([n,x])=><div key={n}><span className="font-mono text-xs text-[#b37a19]">{n}</span><p className="font-display text-xl mt-4">{x}</p></div>)}</div></div></div></section>
  <section id="employers" className="bg-[#e7e1d6] px-6 md:px-12 py-24 md:py-32"><div className="max-w-[1200px] mx-auto grid lg:grid-cols-12 gap-12 items-end"><div className="lg:col-span-8"><p className="text-[#b37a19] text-[11px] uppercase tracking-[.25em] font-bold">For resorts, hotels & guesthouses</p><h2 className="font-display text-5xl md:text-7xl leading-[.9] mt-5 tracking-[-.04em]">Your next<br/><i>great hire</i><br/>is out there.</h2></div><div className="lg:col-span-4"><p className="text-[#637187] leading-relaxed">Tell us who you need. We help screen applications, identify strong candidates and build an interview-ready shortlist, so you can focus on running your business.</p><div className="flex flex-col gap-3 mt-8"><LinkButton>Request candidates <ArrowRight size={17}/></LinkButton><a href="#" className="border border-[#12243f] px-6 py-4 text-center text-xs uppercase tracking-[.12em] font-bold">Employer workspace</a></div></div></div></section>
  <footer className="bg-[#12243f] text-white px-6 md:px-12 py-20"><div className="max-w-[1440px] mx-auto flex flex-col md:flex-row justify-between gap-12"><div><p className="font-display text-3xl">The Jobs MV</p><p className="text-white/55 text-sm mt-3">Right Talent. Right Opportunity. Right Time.</p></div><div className="flex gap-12 text-xs uppercase tracking-[.15em] font-bold text-white/70"><a href="#opportunities">Find jobs</a><a href="#passport">Passport</a><a href="#employers">Employers</a></div></div></footer>
 </main>;
}