// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jobs-home-visual/Current.tsx": () => import("../components/mockups/jobs-home-visual/Current.tsx"),
  "./components/mockups/jobs-home-visual/RefinedEditorial.tsx": () => import("../components/mockups/jobs-home-visual/RefinedEditorial.tsx")
};
